
CREATE TABLE IF NOT EXISTS homepage_content (
  id INT PRIMARY KEY DEFAULT 1,
  stats_churches TEXT NOT NULL,
  stats_pastors TEXT NOT NULL,
  stats_lives TEXT NOT NULL,
  stats_countries TEXT NOT NULL,
  hero_headline TEXT NOT NULL,
  hero_subheadline TEXT NOT NULL,
  hero_image_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE homepage_content ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on homepage_content" ON homepage_content FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to insert homepage_content" ON homepage_content FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update homepage_content" ON homepage_content FOR UPDATE USING (auth.role() = 'authenticated');

CREATE TABLE IF NOT EXISTS events (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  location TEXT NOT NULL,
  description TEXT NOT NULL,
  is_major BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on events" ON events FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to insert events" ON events FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update events" ON events FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete events" ON events FOR DELETE USING (auth.role() = 'authenticated');

-- Storage Buckets
INSERT INTO storage.buckets (id, name, public) VALUES ('media', 'media', true) ON CONFLICT DO NOTHING;

CREATE POLICY "Allow public read access on media" ON storage.objects FOR SELECT USING (bucket_id = 'media');
CREATE POLICY "Allow authenticated users to upload media" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'media' AND auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete media" ON storage.objects FOR DELETE USING (bucket_id = 'media' AND auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update media" ON storage.objects FOR UPDATE USING (bucket_id = 'media' AND auth.role() = 'authenticated');
